#!/usr/bin/env bash
# configure the domain.


function calledonce () {
	for subdomain in "www" "lb-01" "web-01" "web-02"
	do
		dig "$subdomain.$1" | grep -A1 'ANSWER SECTION:' | awk "/$1/ {print \"The subdomain $subdomain \" \"is a \" \$4 \" record and points to \" \$5}";
	done
}

function calledtwice () {
	dig "$2"."$1" | grep -A1 'ANSWER SECTION:' | awk "/$2/ {print \"The subdomain $2 \" \"is a \" \$4 \" record and points to \" \$5}";
}
if [ $1 ] && [ ! $2 ]
then
	domain=$1;
	calledonce $domain;
elif [ $2 ]
then
	domain=$1;
	subdomain=$2;
	calledtwice $domain $subdomain;
fi
