#!/usr/bin/env bash
# install nginx and configure it.

sudo apt-get -y update;
sudo apt-get -y install nginx;
sudo chown -R $USER:$USER /var/www/html;
sudo chmod -R 755 /var/www;
sudo echo 'Hello World!' > /var/www/html/index.nginx-debian.html;
sudo service nginx start;
