#!/usr/bin/env bash
# install nginx and configure it.

sudo apt -y update;
sudo apt -y install nginx;
sudo echo "Hello World!" > /var/www/html/index.nginx-debian.html;
sudo ufw allow 'Nginx HTTP';
sudo service nginx start;
