#!/usr/bin/env bash
# install nginx and configure it.

sudo apt-get -y update;
sudo apt-get -y install nginx;
sudo chown -R "$USER":"$USER" /var/www/html;
sudo chmod -R 755 /var/www;
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html;
echo "Ceci n'est pas une page" | sudo tee /var/www/html/error-404.html;

string_to_replace="server_name _;";
file="/etc/nginx/sites-enabled/default";

# configure the server to redirect the page '/redirect_me' to another page.
new_line1="location \/redirect_me \{"
new_line2="\n\t\treturn 301 \$scheme:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t\}";
new_string="${new_line1}${new_line2}\n\t${string_to_replace}";
if ! grep -Pxq "\t$new_line1" $file
then
        sudo sed -i "s/$string_to_replace/$new_string/" $file;
fi

# create a custom error 404 page.
new_line="error_page 404 \/error-404.html;"
new_string="${new_line}\n\t${string_to_replace}";
if ! grep -Pxq "\t$new_line" $file
then
        sudo sed -i "s/$string_to_replace/$new_string/" $file;
fi

# create a custom error 404 page.
new_line="add_header X-Served-By $HOSTNAME;"
new_string="${new_line}\n\t${string_to_replace}";
if ! grep -Pxq "\t$new_line" $file
then
        sudo sed -i "s/$string_to_replace/$new_string/" $file;
fi

sudo service nginx restart;
