#!/usr/bin/env bash
# control my_process.

pidfile="/var/run/my_process.pid";
process="./manage_my_process";

if [ "$1" ];
then
	if [ "$2" ];
	then
		echo "Usage: manage_my_process {start|stop|restart}";
		exit;
	fi

	# Handle [start|stop|restart]
	if [ "$1" = "start" ];
	then
		$process &
		echo $! > "$pidfile"
		echo "manage_my_process started";
	elif [ "$1" = "stop" ];
	then
		pkill -f "$process"
		rm $pidfile
		echo "manage_my_process stopped";
	elif [ "$1" = "restart" ];
	then
		pkill -f "$process"
		rm $pidfile
		$process &
		echo $! > "$pidfile"
		echo "manage_my_process restarted";
	else
		echo "Usage: manage_my_process {start|stop|restart}";
	fi
	# --------------------------

else
	echo "Usage: manage_my_process {start|stop|restart}";
fi
