#!/usr/bin/env bash
# displays the time for 12 hours and 59 minutes.

hours=0
minutes=1

while [ $hours -le 12 ];
do
	minutes=1;
	echo "Hour: $hours";
	while [ $minutes -lt 60 ];
	do
		echo $minutes;
		(( minutes++ ));
	done
	(( hours++ ));
done
