#!/usr/bin/env bash
# find and replace a line in host file.

file="/etc/hosts"
newfile="~/hosts.new"
l1="$(grep localhost$ -n < $file | cut -d ":" -f 1)"
l2="$(grep facebook.com$ -n < $file | cut -d ":" -f 1)"
n=1
echo "" > "$newfile"
while read -r line
do
	if [ $n -eq "$l1" ]
	then
		echo "127.0.0.2	localhost" >> "$newfile"
	elif [ "$l2" ] && [ $n -eq "$l2" ]
	then
		echo "8.8.8.8	facebook.com" >> "$newfile"
	else
		echo "$line" >> "$newfile"
	fi
	(( n++ ));
done < "$file"
if [ ! "$l2" ];
then
	echo "8.8.8.8   facebook.com" >> "$newfile"
fi
cp -f "$newfile" "$file"
